<?php

declare(strict_types=1);

namespace Nos\DadataApi\DTO;

use Nos\BaseDto\Interfaces\DtoInterface;
use Nos\BaseDto\Traits\DataTransforms\ArrayDataTransformable;

final readonly class AddressDTO implements DtoInterface
{
    use ArrayDataTransformable;

    /**
     * @param array<MetroDTO>|null $metro
     * @param DivisionsDTO|null $divisions
     */
    private function __construct(
        public string $source,
        public string $result,
        public ?string $postalCode,
        public string $country,
        public string $countryIsoCode,
        public ?string $federalDistrict,
        public string $regionFiasId,
        public string $regionKladrId,
        public ?string $regionIsoCode,
        public string $regionWithType,
        public string $regionType,
        public ?string $regionTypeFull,
        public string $region,
        public ?string $areaFiasId,
        public ?string $areaKladrId,
        public ?string $areaWithType,
        public ?string $areaType,
        public ?string $areaTypeFull,
        public ?string $area,
        public ?string $cityFiasId,
        public ?string $cityKladrId,
        public ?string $cityWithType,
        public ?string $cityType,
        public ?string $cityTypeFull,
        public ?string $city,
        public ?string $cityArea,
        public ?string $cityDistrictFiasId,
        public ?string $cityDistrictKladrId,
        public ?string $cityDistrictWithType,
        public ?string $cityDistrictType,
        public ?string $cityDistrictTypeFull,
        public ?string $cityDistrict,
        public ?string $settlementFiasId,
        public ?string $settlementKladrId,
        public ?string $settlementWithType,
        public ?string $settlementType,
        public ?string $settlementTypeFull,
        public ?string $settlement,
        public string $streetFiasId,
        public string $streetKladrId,
        public string $streetWithType,
        public string $streetType,
        public ?string $streetTypeFull,
        public string $street,
        public ?string $steadFiasId,
        public ?string $steadKladrId,
        public ?string $steadCadnum,
        public ?string $steadType,
        public ?string $steadTypeFull,
        public ?string $stead,
        public string $houseFiasId,
        public string $houseKladrId,
        public ?string $houseCadnum,
        public string $houseType,
        public ?string $houseTypeFull,
        public string $house,
        public ?string $houseFlatCount,
        public ?string $blockType,
        public ?string $blockTypeFull,
        public ?string $block,
        public ?string $entrance,
        public ?string $floor,
        public ?string $flatFiasId,
        public ?string $flatCadnum,
        public string $flatType,
        public ?string $flatTypeFull,
        public string $flat,
        public ?string $flatArea,
        public ?string $squareMeterPrice,
        public ?string $flatPrice,
        public ?string $postalBox,
        public ?string $roomType,
        public ?string $roomTypeFull,
        public ?string $room,
        public string $fiasId,
        public ?string $fiasCode,
        public string $fiasLevel,
        public string $fiasActualityState,
        public string $kladrId,
        public ?string $geonameId,
        public ?string $capitalMarker,
        public ?string $okato,
        public ?string $oktmo,
        public ?string $taxOffice,
        public ?string $taxOfficeLegal,
        public ?string $timezone,
        public ?string $geoLat,
        public ?string $geoLon,
        public ?string $beltwayHit,
        public ?string $beltwayDistance,
        public int $qcGeo,
        public int $qcComplete,
        public int $qcHouse,
        public int $qc,
        public ?string $unparsedParts,
        public ?array $metro,
        public ?DivisionsDTO $divisions,
    ) {}

    public static function fromArray(array $data): self
    {
        $metro = null;
        if (isset($data['metro']) && is_array($data['metro'])) {
            $metro = array_map(
                static fn(array $m): MetroDTO => MetroDTO::fromArray($m),
                $data['metro']
            );
        }

        $divisions = null;
        if (isset($data['divisions']) && is_array($data['divisions'])) {
            $divisions = DivisionsDTO::fromArray($data['divisions']);
        }

        return new self(
            source: $data['source'] ?? '',
            result: $data['result'] ?? $data['unrestricted_value'] ?? $data['value'] ?? '',
            postalCode: $data['postal_code'] ?? null,
            country: $data['country'] ?? '',
            countryIsoCode: $data['country_iso_code'] ?? '',
            federalDistrict: $data['federal_district'] ?? null,
            regionFiasId: $data['region_fias_id'] ?? '',
            regionKladrId: $data['region_kladr_id'] ?? '',
            regionIsoCode: $data['region_iso_code'] ?? null,
            regionWithType: $data['region_with_type'] ?? '',
            regionType: $data['region_type'] ?? '',
            regionTypeFull: $data['region_type_full'] ?? null,
            region: $data['region'] ?? '',
            areaFiasId: $data['area_fias_id'] ?? null,
            areaKladrId: $data['area_kladr_id'] ?? null,
            areaWithType: $data['area_with_type'] ?? null,
            areaType: $data['area_type'] ?? null,
            areaTypeFull: $data['area_type_full'] ?? null,
            area: $data['area'] ?? null,
            cityFiasId: $data['city_fias_id'] ?? null,
            cityKladrId: $data['city_kladr_id'] ?? null,
            cityWithType: $data['city_with_type'] ?? null,
            cityType: $data['city_type'] ?? null,
            cityTypeFull: $data['city_type_full'] ?? null,
            city: $data['city'] ?? null,
            cityArea: $data['city_area'] ?? null,
            cityDistrictFiasId: $data['city_district_fias_id'] ?? null,
            cityDistrictKladrId: $data['city_district_kladr_id'] ?? null,
            cityDistrictWithType: $data['city_district_with_type'] ?? null,
            cityDistrictType: $data['city_district_type'] ?? null,
            cityDistrictTypeFull: $data['city_district_type_full'] ?? null,
            cityDistrict: $data['city_district'] ?? null,
            settlementFiasId: $data['settlement_fias_id'] ?? null,
            settlementKladrId: $data['settlement_kladr_id'] ?? null,
            settlementWithType: $data['settlement_with_type'] ?? null,
            settlementType: $data['settlement_type'] ?? null,
            settlementTypeFull: $data['settlement_type_full'] ?? null,
            settlement: $data['settlement'] ?? null,
            streetFiasId: $data['street_fias_id'] ?? '',
            streetKladrId: $data['street_kladr_id'] ?? '',
            streetWithType: $data['street_with_type'] ?? '',
            streetType: $data['street_type'] ?? '',
            streetTypeFull: $data['street_type_full'] ?? null,
            street: $data['street'] ?? '',
            steadFiasId: $data['stead_fias_id'] ?? null,
            steadKladrId: $data['stead_kladr_id'] ?? null,
            steadCadnum: $data['stead_cadnum'] ?? null,
            steadType: $data['stead_type'] ?? null,
            steadTypeFull: $data['stead_type_full'] ?? null,
            stead: $data['stead'] ?? null,
            houseFiasId: $data['house_fias_id'] ?? '',
            houseKladrId: $data['house_kladr_id'] ?? '',
            houseCadnum: $data['house_cadnum'] ?? null,
            houseType: $data['house_type'] ?? '',
            houseTypeFull: $data['house_type_full'] ?? null,
            house: $data['house'] ?? '',
            houseFlatCount: $data['house_flat_count'] ?? null,
            blockType: $data['block_type'] ?? null,
            blockTypeFull: $data['block_type_full'] ?? null,
            block: $data['block'] ?? null,
            entrance: $data['entrance'] ?? null,
            floor: $data['floor'] ?? null,
            flatFiasId: $data['flat_fias_id'] ?? null,
            flatCadnum: $data['flat_cadnum'] ?? null,
            flatType: $data['flat_type'] ?? '',
            flatTypeFull: $data['flat_type_full'] ?? null,
            flat: $data['flat'] ?? '',
            flatArea: $data['flat_area'] ?? null,
            squareMeterPrice: $data['square_meter_price'] ?? null,
            flatPrice: $data['flat_price'] ?? null,
            postalBox: $data['postal_box'] ?? null,
            roomType: $data['room_type'] ?? null,
            roomTypeFull: $data['room_type_full'] ?? null,
            room: $data['room'] ?? null,
            fiasId: $data['fias_id'] ?? '',
            fiasCode: $data['fias_code'] ?? null,
            fiasLevel: $data['fias_level'] ?? '',
            fiasActualityState: $data['fias_actuality_state'] ?? '',
            kladrId: $data['kladr_id'] ?? '',
            geonameId: $data['geoname_id'] ?? null,
            capitalMarker: $data['capital_marker'] ?? null,
            okato: $data['okato'] ?? null,
            oktmo: $data['oktmo'] ?? null,
            taxOffice: $data['tax_office'] ?? null,
            taxOfficeLegal: $data['tax_office_legal'] ?? null,
            timezone: $data['timezone'] ?? null,
            geoLat: $data['geo_lat'] ?? null,
            geoLon: $data['geo_lon'] ?? null,
            beltwayHit: $data['beltway_hit'] ?? null,
            beltwayDistance: $data['beltway_distance'] ?? null,
            qcGeo: (int) ($data['qc_geo'] ?? 0),
            qcComplete: (int) ($data['qc_complete'] ?? 0),
            qcHouse: (int) ($data['qc_house'] ?? 0),
            qc: (int) ($data['qc'] ?? 0),
            unparsedParts: $data['unparsed_parts'] ?? null,
            metro: $metro,
            divisions: $divisions,
        );
    }
}
