<?php

declare(strict_types=1);

namespace Nos\DadataApi\DTO;

use Nos\BaseDto\Interfaces\DtoInterface;
use Nos\BaseDto\Traits\DataTransforms\ArrayDataTransformable;

final readonly class AddressSuggestionDTO implements DtoInterface
{
    use ArrayDataTransformable;

    /**
     * @param array<int, MetroDTO>|null $metro
     * @param DivisionsDTO|null $divisions
     */
    private function __construct(
        public string $value,
        public string $unrestrictedValue,
        public string $kladrId,
        public string $fiasId,
        public string $fiasGuid,
        public string $fiasLevel,
        public string $fiasPath,
        public string $fiasBlanked,
        public ?string $addressType,
        public ?string $address,
        public ?string $source,
        public ?string $result,
        public ?string $postalCode,
        public ?string $country,
        public ?string $countryIsoCode,
        public ?string $federalDistrict,
        public ?string $regionFiasId,
        public ?string $regionKladrId,
        public ?string $regionIsoCode,
        public ?string $regionWithType,
        public ?string $regionType,
        public ?string $regionTypeFull,
        public ?string $region,
        public ?string $areaFiasId,
        public ?string $areaKladrId,
        public ?string $areaWithType,
        public ?string $areaType,
        public ?string $areaTypeFull,
        public ?string $area,
        public ?string $cityFiasId,
        public ?string $cityKladrId,
        public ?string $cityWithType,
        public ?string $cityType,
        public ?string $cityTypeFull,
        public ?string $city,
        public ?string $cityArea,
        public ?string $cityDistrictFiasId,
        public ?string $cityDistrictKladrId,
        public ?string $cityDistrictWithType,
        public ?string $cityDistrictType,
        public ?string $cityDistrictTypeFull,
        public ?string $cityDistrict,
        public ?string $settlementFiasId,
        public ?string $settlementKladrId,
        public ?string $settlementWithType,
        public ?string $settlementType,
        public ?string $settlementTypeFull,
        public ?string $settlement,
        public string $streetFiasId,
        public string $streetKladrId,
        public string $streetWithType,
        public string $streetType,
        public ?string $streetTypeFull,
        public string $street,
        public ?string $steadFiasId,
        public ?string $steadKladrId,
        public ?string $steadCadnum,
        public ?string $steadType,
        public ?string $steadTypeFull,
        public ?string $stead,
        public string $houseFiasId,
        public string $houseKladrId,
        public ?string $houseCadnum,
        public string $houseType,
        public ?string $houseTypeFull,
        public string $house,
        public ?string $houseFlatCount,
        public ?string $blockType,
        public ?string $blockTypeFull,
        public ?string $block,
        public ?string $entrance,
        public ?string $floor,
        public ?string $flatFiasId,
        public ?string $flatCadnum,
        public string $flatType,
        public ?string $flatTypeFull,
        public string $flat,
        public ?string $flatArea,
        public ?string $squareMeterPrice,
        public ?string $flatPrice,
        public ?string $postalBox,
        public ?string $roomType,
        public ?string $roomTypeFull,
        public ?string $room,
        public ?string $fiasCode,
        public string $fiasActualityState,
        public ?string $geonameId,
        public ?string $capitalMarker,
        public ?string $okato,
        public ?string $oktmo,
        public ?string $taxOffice,
        public ?string $taxOfficeLegal,
        public ?string $timezone,
        public ?string $geoLat,
        public ?string $geoLon,
        public ?string $beltwayHit,
        public ?string $beltwayDistance,
        public int $qcGeo,
        public int $qcComplete,
        public int $qcHouse,
        public int $qc,
        public ?string $unparsedParts,
        public ?array $metro,
        public ?DivisionsDTO $divisions,
    ) {}

    public static function fromArray(array $data): self
    {
        $payload = is_array($data['data'] ?? null) ? $data['data'] : [];

        $metro = null;
        if (isset($payload['metro']) && is_array($payload['metro'])) {
            $metro = array_map(
                static fn(array $m): MetroDTO => MetroDTO::fromArray($m),
                $payload['metro']
            );
        }

        $divisions = null;
        if (isset($payload['divisions']) && is_array($payload['divisions'])) {
            $divisions = DivisionsDTO::fromArray($payload['divisions']);
        }

        return new self(
            value: $data['value'] ?? '',
            unrestrictedValue: $data['unrestricted_value'] ?? '',
            kladrId: $payload['kladr_id'] ?? '',
            fiasId: $payload['fias_id'] ?? '',
            fiasGuid: $payload['fias_guid'] ?? '',
            fiasLevel: $payload['fias_level'] ?? '',
            fiasPath: $payload['fias_path'] ?? '',
            fiasBlanked: $payload['fias_blanked'] ?? '',
            addressType: $payload['address_type'] ?? null,
            address: $payload['address'] ?? null,
            source: $payload['source'] ?? null,
            result: $payload['result'] ?? null,
            postalCode: $payload['postal_code'] ?? null,
            country: $payload['country'] ?? null,
            countryIsoCode: $payload['country_iso_code'] ?? null,
            federalDistrict: $payload['federal_district'] ?? null,
            regionFiasId: $payload['region_fias_id'] ?? null,
            regionKladrId: $payload['region_kladr_id'] ?? null,
            regionIsoCode: $payload['region_iso_code'] ?? null,
            regionWithType: $payload['region_with_type'] ?? null,
            regionType: $payload['region_type'] ?? null,
            regionTypeFull: $payload['region_type_full'] ?? null,
            region: $payload['region'] ?? null,
            areaFiasId: $payload['area_fias_id'] ?? null,
            areaKladrId: $payload['area_kladr_id'] ?? null,
            areaWithType: $payload['area_with_type'] ?? null,
            areaType: $payload['area_type'] ?? null,
            areaTypeFull: $payload['area_type_full'] ?? null,
            area: $payload['area'] ?? null,
            cityFiasId: $payload['city_fias_id'] ?? null,
            cityKladrId: $payload['city_kladr_id'] ?? null,
            cityWithType: $payload['city_with_type'] ?? null,
            cityType: $payload['city_type'] ?? null,
            cityTypeFull: $payload['city_type_full'] ?? null,
            city: $payload['city'] ?? null,
            cityArea: $payload['city_area'] ?? null,
            cityDistrictFiasId: $payload['city_district_fias_id'] ?? null,
            cityDistrictKladrId: $payload['city_district_kladr_id'] ?? null,
            cityDistrictWithType: $payload['city_district_with_type'] ?? null,
            cityDistrictType: $payload['city_district_type'] ?? null,
            cityDistrictTypeFull: $payload['city_district_type_full'] ?? null,
            cityDistrict: $payload['city_district'] ?? null,
            settlementFiasId: $payload['settlement_fias_id'] ?? null,
            settlementKladrId: $payload['settlement_kladr_id'] ?? null,
            settlementWithType: $payload['settlement_with_type'] ?? null,
            settlementType: $payload['settlement_type'] ?? null,
            settlementTypeFull: $payload['settlement_type_full'] ?? null,
            settlement: $payload['settlement'] ?? null,
            streetFiasId: $payload['street_fias_id'] ?? '',
            streetKladrId: $payload['street_kladr_id'] ?? '',
            streetWithType: $payload['street_with_type'] ?? '',
            streetType: $payload['street_type'] ?? '',
            streetTypeFull: $payload['street_type_full'] ?? null,
            street: $payload['street'] ?? '',
            steadFiasId: $payload['stead_fias_id'] ?? null,
            steadKladrId: $payload['stead_kladr_id'] ?? null,
            steadCadnum: $payload['stead_cadnum'] ?? null,
            steadType: $payload['stead_type'] ?? null,
            steadTypeFull: $payload['stead_type_full'] ?? null,
            stead: $payload['stead'] ?? null,
            houseFiasId: $payload['house_fias_id'] ?? '',
            houseKladrId: $payload['house_kladr_id'] ?? '',
            houseCadnum: $payload['house_cadnum'] ?? null,
            houseType: $payload['house_type'] ?? '',
            houseTypeFull: $payload['house_type_full'] ?? null,
            house: $payload['house'] ?? '',
            houseFlatCount: $payload['house_flat_count'] ?? null,
            blockType: $payload['block_type'] ?? null,
            blockTypeFull: $payload['block_type_full'] ?? null,
            block: $payload['block'] ?? null,
            entrance: $payload['entrance'] ?? null,
            floor: $payload['floor'] ?? null,
            flatFiasId: $payload['flat_fias_id'] ?? null,
            flatCadnum: $payload['flat_cadnum'] ?? null,
            flatType: $payload['flat_type'] ?? '',
            flatTypeFull: $payload['flat_type_full'] ?? null,
            flat: $payload['flat'] ?? '',
            flatArea: $payload['flat_area'] ?? null,
            squareMeterPrice: $payload['square_meter_price'] ?? null,
            flatPrice: $payload['flat_price'] ?? null,
            postalBox: $payload['postal_box'] ?? null,
            roomType: $payload['room_type'] ?? null,
            roomTypeFull: $payload['room_type_full'] ?? null,
            room: $payload['room'] ?? null,
            fiasCode: $payload['fias_code'] ?? null,
            fiasActualityState: $payload['fias_actuality_state'] ?? '',
            geonameId: $payload['geoname_id'] ?? null,
            capitalMarker: $payload['capital_marker'] ?? null,
            okato: $payload['okato'] ?? null,
            oktmo: $payload['oktmo'] ?? null,
            taxOffice: $payload['tax_office'] ?? null,
            taxOfficeLegal: $payload['tax_office_legal'] ?? null,
            timezone: $payload['timezone'] ?? null,
            geoLat: $payload['geo_lat'] ?? null,
            geoLon: $payload['geo_lon'] ?? null,
            beltwayHit: $payload['beltway_hit'] ?? null,
            beltwayDistance: $payload['beltway_distance'] ?? null,
            qcGeo: isset($payload['qc_geo']) ? (int) $payload['qc_geo'] : 0,
            qcComplete: isset($payload['qc_complete']) ? (int) $payload['qc_complete'] : 0,
            qcHouse: isset($payload['qc_house']) ? (int) $payload['qc_house'] : 0,
            qc: isset($payload['qc']) ? (int) $payload['qc'] : 0,
            unparsedParts: $payload['unparsed_parts'] ?? null,
            metro: $metro,
            divisions: $divisions,
        );
    }
}
