<?php

declare(strict_types=1);

namespace Nos\DadataApi\DTO;

use Nos\BaseDto\Interfaces\DtoInterface;
use Nos\BaseDto\Traits\DataTransforms\ArrayDataTransformable;

final readonly class SuggestionDataDTO implements DtoInterface
{
    use ArrayDataTransformable;

    private function __construct(
        public string $kladrId = '',
        public string $fiasId = '',
        public string $fiasGuid = '',
        public string $fiasLevel = '',
        public string $fiasPath = '',
        public string $fiasBlanked = '',
        public ?string $addressType = '',
        public ?string $address = '',
        public ?string $source = '',
        public ?string $result = '',
        public ?string $postalCode = '',
        public ?string $country = '',
        public ?string $countryIsoCode = '',
        public ?string $federalDistrict = '',
        public ?string $regionFiasId = '',
        public ?string $regionKladrId = '',
        public ?string $regionWithType = '',
        public ?string $regionType = '',
        public ?string $region = '',
        public ?string $areaFiasId = '',
        public ?string $areaKladrId = '',
        public ?string $areaWithType = '',
        public ?string $areaType = '',
        public ?string $area = '',
        public ?string $cityFiasId = '',
        public ?string $cityKladrId = '',
        public ?string $cityWithType = '',
        public ?string $cityType = '',
        public ?string $cityArea = '',
        public ?string $cityDistrictFiasId = '',
        public ?string $cityDistrictKladrId = '',
        public ?string $cityDistrictWithType = '',
        public ?string $cityDistrictType = '',
        public ?string $cityDistrict = '',
        public ?string $settlementFiasId = '',
        public ?string $settlementKladrId = '',
        public ?string $settlementWithType = '',
        public ?string $settlementType = '',
        public ?string $settlement = '',
        public ?string $streetFiasId = '',
        public ?string $streetKladrId = '',
        public ?string $streetWithType = '',
        public ?string $streetType = '',
        public ?string $street = '',
        public ?string $houseFiasId = '',
        public ?string $houseKladrId = '',
        public ?string $houseType = '',
        public ?string $house = '',
        public ?string $houseCadnum = '',
        public ?string $houseFlatCount = '',
        public ?string $flatType = '',
        public ?string $flat = '',
        public ?string $flatFiasId = '',
        public ?string $flatCadnum = '',
        public ?string $flatArea = '',
        public ?string $flatPrice = '',
        public ?string $flatFloor = '',
        public ?string $floorsCount = '',
        public ?string $houseFloorCount = '',
        public ?string $buildYear = '',
        public ?string $buildSection = '',
        public ?string $qcComplete = '',
        public ?string $qcGeo = '',
        public ?string $qcHouse = '',
        public ?string $qcFlat = '',
        public ?string $unrestrictedValue = '',
        public ?string $boxberryId = '',
        public ?string $cdekId = '',
        public ?string $dpdId = '',
        public ?string $name = '',
        public ?string $fullName = '',
        public ?string $shortName = '',
        public ?string $inn = '',
        public ?string $kpp = '',
        public ?string $ogrn = '',
        public ?string $ogrnDate = '',
        public ?string $opf = '',
        public ?string $opfShort = '',
        public ?string $addressWord = '',
        public ?string $state = '',
        public ?string $stateStatus = '',
        public ?string $stateActualityDate = '',
        public ?string $bankBic = '',
        public ?string $swift = '',
        public ?string $okato = '',
        public ?string $tks = '',
        public ?string $type = '',
        public ?string $phone = '',
        public ?string $countryCode = '',
        public ?string $cityCode = '',
        public ?string $number = '',
        public ?string $extension = '',
        public ?string $provider = '',
        public ?string $regionCode = '',
        public ?string $timezone = '',
        public ?string $qcConflicting = '',
        public ?string $email = '',
        public ?string $url = '',
        public ?string $fms = '',
        public ?string $geonameId = '',
        public ?string $capitalMarker = '',
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            kladrId: $data['kladr_id'] ?? '',
            fiasId: $data['fias_id'] ?? '',
            fiasGuid: $data['fias_guid'] ?? '',
            fiasLevel: $data['fias_level'] ?? '',
            fiasPath: $data['fias_path'] ?? '',
            fiasBlanked: $data['fias_blanked'] ?? '',
            addressType: $data['address_type'] ?? null,
            address: $data['address'] ?? null,
            source: $data['source'] ?? null,
            result: $data['result'] ?? null,
            postalCode: $data['postal_code'] ?? null,
            country: $data['country'] ?? null,
            countryIsoCode: $data['country_iso_code'] ?? null,
            federalDistrict: $data['federal_district'] ?? null,
            regionFiasId: $data['region_fias_id'] ?? null,
            regionKladrId: $data['region_kladr_id'] ?? null,
            regionWithType: $data['region_with_type'] ?? null,
            regionType: $data['region_type'] ?? null,
            region: $data['region'] ?? null,
            areaFiasId: $data['area_fias_id'] ?? null,
            areaKladrId: $data['area_kladr_id'] ?? null,
            areaWithType: $data['area_with_type'] ?? null,
            areaType: $data['area_type'] ?? null,
            area: $data['area'] ?? null,
            cityFiasId: $data['city_fias_id'] ?? null,
            cityKladrId: $data['city_kladr_id'] ?? null,
            cityWithType: $data['city_with_type'] ?? null,
            cityType: $data['city_type'] ?? null,
            cityArea: $data['city_area'] ?? null,
            cityDistrictFiasId: $data['city_district_fias_id'] ?? null,
            cityDistrictKladrId: $data['city_district_kladr_id'] ?? null,
            cityDistrictWithType: $data['city_district_with_type'] ?? null,
            cityDistrictType: $data['city_district_type'] ?? null,
            cityDistrict: $data['city_district'] ?? null,
            settlementFiasId: $data['settlement_fias_id'] ?? null,
            settlementKladrId: $data['settlement_kladr_id'] ?? null,
            settlementWithType: $data['settlement_with_type'] ?? null,
            settlementType: $data['settlement_type'] ?? null,
            settlement: $data['settlement'] ?? null,
            streetFiasId: $data['street_fias_id'] ?? null,
            streetKladrId: $data['street_kladr_id'] ?? null,
            streetWithType: $data['street_with_type'] ?? null,
            streetType: $data['street_type'] ?? null,
            street: $data['street'] ?? null,
            houseFiasId: $data['house_fias_id'] ?? null,
            houseKladrId: $data['house_kladr_id'] ?? null,
            houseType: $data['house_type'] ?? null,
            house: $data['house'] ?? null,
            houseCadnum: $data['house_cadnum'] ?? null,
            houseFlatCount: $data['house_flat_count'] ?? null,
            flatType: $data['flat_type'] ?? null,
            flat: $data['flat'] ?? null,
            flatFiasId: $data['flat_fias_id'] ?? null,
            flatCadnum: $data['flat_cadnum'] ?? null,
            flatArea: $data['flat_area'] ?? null,
            flatPrice: $data['flat_price'] ?? null,
            flatFloor: $data['flat_floor'] ?? null,
            floorsCount: $data['floors_count'] ?? null,
            houseFloorCount: $data['house_floor_count'] ?? null,
            buildYear: $data['build_year'] ?? null,
            buildSection: $data['build_section'] ?? null,
            qcComplete: $data['qc_complete'] ?? null,
            qcGeo: $data['qc_geo'] ?? null,
            qcHouse: $data['qc_house'] ?? null,
            qcFlat: $data['qc_flat'] ?? null,
            unrestrictedValue: $data['unrestricted_value'] ?? null,
            boxberryId: $data['boxberry_id'] ?? null,
            cdekId: $data['cdek_id'] ?? null,
            dpdId: $data['dpd_id'] ?? null,
            name: $data['name'] ?? null,
            fullName: $data['full_name'] ?? null,
            shortName: $data['short_name'] ?? null,
            inn: $data['inn'] ?? null,
            kpp: $data['kpp'] ?? null,
            ogrn: $data['ogrn'] ?? null,
            ogrnDate: $data['ogrn_date'] ?? null,
            opf: $data['opf'] ?? null,
            opfShort: $data['opf_short'] ?? null,
            addressWord: $data['address_word'] ?? null,
            state: $data['state'] ?? null,
            stateStatus: $data['state_status'] ?? null,
            stateActualityDate: $data['state_actuality_date'] ?? null,
            bankBic: $data['bik'] ?? null,
            swift: $data['swift'] ?? null,
            okato: $data['okato'] ?? null,
            tks: $data['tks'] ?? null,
            type: $data['type'] ?? null,
            phone: $data['phone'] ?? null,
            countryCode: $data['country_code'] ?? null,
            cityCode: $data['city_code'] ?? null,
            number: $data['number'] ?? null,
            extension: $data['extension'] ?? null,
            provider: $data['provider'] ?? null,
            regionCode: $data['region_code'] ?? null,
            timezone: $data['timezone'] ?? null,
            qcConflicting: $data['qc_conflicting'] ?? null,
            email: $data['email'] ?? null,
            url: $data['url'] ?? null,
            fms: $data['fms'] ?? null,
            geonameId: $data['geoname_id'] ?? null,
            capitalMarker: $data['capital_marker'] ?? null,
        );
    }
}